// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellRoute.DataAccess.Context;

#nullable disable

namespace WellRoute.DataAccess.Migrations
{
    [DbContext(typeof(WellRouteDbContext))]
    partial class WellRouteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WellRoute.Models.Entities.Permiso", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermisoID");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoID = 1,
                            Codigo = "user.create",
                            Descripcion = "Permiso para crear nuevos usuarios",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Crear Usuario"
                        },
                        new
                        {
                            PermisoID = 2,
                            Codigo = "user.read",
                            Descripcion = "Permiso para ver información de usuarios",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ver Usuario"
                        },
                        new
                        {
                            PermisoID = 3,
                            Codigo = "user.update",
                            Descripcion = "Permiso para editar usuarios",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Editar Usuario"
                        },
                        new
                        {
                            PermisoID = 4,
                            Codigo = "user.deactivate",
                            Descripcion = "Permiso para desactivar usuarios",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Desactivar Usuario"
                        },
                        new
                        {
                            PermisoID = 5,
                            Codigo = "destino.create",
                            Descripcion = "Permiso para crear destinos",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Crear Destino"
                        },
                        new
                        {
                            PermisoID = 6,
                            Codigo = "destino.read",
                            Descripcion = "Permiso para ver destinos",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ver Destino"
                        },
                        new
                        {
                            PermisoID = 7,
                            Codigo = "destino.update",
                            Descripcion = "Permiso para editar destinos",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Editar Destino"
                        },
                        new
                        {
                            PermisoID = 8,
                            Codigo = "destino.deactivate",
                            Descripcion = "Permiso para desactivar destinos",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Desactivar Destino"
                        },
                        new
                        {
                            PermisoID = 9,
                            Codigo = "admin.access",
                            Descripcion = "Permiso para acceder al panel administrativo",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Acceso Admin"
                        });
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            Activo = true,
                            Descripcion = "Rol con acceso completo al sistema",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolID = 2,
                            Activo = true,
                            Descripcion = "Rol para editar contenido",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Editor"
                        },
                        new
                        {
                            RolID = 3,
                            Activo = true,
                            Descripcion = "Rol estándar para usuarios regulares",
                            FechaCreacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Rol_Permiso", b =>
                {
                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("PermisoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("RolID", "PermisoID");

                    b.HasIndex("PermisoID");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            PermisoID = 1,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 2,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 3,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 4,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 5,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 6,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 7,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 8,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 1,
                            PermisoID = 9,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 2,
                            PermisoID = 2,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 2,
                            PermisoID = 3,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 2,
                            PermisoID = 5,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 2,
                            PermisoID = 6,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 2,
                            PermisoID = 7,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 3,
                            PermisoID = 2,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolID = 3,
                            PermisoID = 6,
                            FechaAsignacion = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaUltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Usuario_Rol", b =>
                {
                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UsuarioID", "RolID");

                    b.HasIndex("RolID");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Rol_Permiso", b =>
                {
                    b.HasOne("WellRoute.Models.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WellRoute.Models.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Usuario_Rol", b =>
                {
                    b.HasOne("WellRoute.Models.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WellRoute.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("WellRoute.Models.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
